// Shared product catalog for سلة البيت family apps
// Edit this ONE file to update the item list across all apps that load it.
window.CATALOG = [
    {id:'produce', name:'خضار وفواكه', emoji:'🥬', items:[
      {id:'tomato', name:'طماطم', emoji:'🍅', aliases:['بندورة','עגבניה']},
      {id:'cucumber', name:'خيار', emoji:'🥒', aliases:['מלפפון']},
      {id:'potato', name:'بطاطا', emoji:'🥔', aliases:['بطاطس','תפוח אדמה']},
      {id:'onion', name:'بصل', emoji:'🧅', aliases:['בצל']},
      {id:'scallion', name:'بصل أخضر', emoji:'🌱', aliases:['بصل اخضر','בצל ירוק']},
      {id:'leek', name:'كراث', emoji:'🌱', aliases:['כרישה']},
      {id:'garlic', name:'ثوم', emoji:'🧄', aliases:['שום']},
      {id:'carrot', name:'جزر', emoji:'🥕', aliases:['גזר']},
      {id:'pepper', name:'فلفل حلو', emoji:'🫑', aliases:['فليفلة','فلفل ألوان','פלפל']},
      {id:'hotpepper', name:'فلفل حار', emoji:'🌶️', aliases:['פלפל חריף']},
      {id:'eggplant', name:'باذنجان', emoji:'🍆', aliases:['بيتنجان','חציל']},
      {id:'zucchini', name:'كوسا', emoji:'🥒', aliases:['كوسة','קישוא']},
      {id:'lettuce', name:'خس', emoji:'🥬', aliases:['חסה']},
      {id:'arugula', name:'جرجير', emoji:'🌿', aliases:['רוקט']},
      {id:'spinach', name:'سبانخ', emoji:'🍃', aliases:['תרד']},
      {id:'parsley', name:'بقدونس', emoji:'🌿', aliases:['פטרוזיליה']},
      {id:'mint', name:'نعناع', emoji:'🌿', aliases:['נענע']},
      {id:'cilantro', name:'كزبرة', emoji:'🌿', aliases:['كسبرة','כוסברה']},
      {id:'celery', name:'كرفس', emoji:'🌿', aliases:['סלרי']},
      {id:'lemon', name:'ليمون', emoji:'🍋', aliases:['לימון']},
      {id:'lime', name:'ليمون أخضر', emoji:'🍈', aliases:['لايم','ליים']},
      {id:'apple', name:'تفاح', emoji:'🍎', aliases:['תפוח']},
      {id:'banana', name:'موز', emoji:'🍌', aliases:['בננה']},
      {id:'orange', name:'برتقال', emoji:'🍊', aliases:['תפוז']},
      {id:'mandarin', name:'يوسفي', emoji:'🍊', aliases:['مندلينا','קלמנטינה']},
      {id:'grapefruit', name:'جريب فروت', emoji:'🍊', aliases:['אשכולית']},
      {id:'grape', name:'عنب', emoji:'🍇', aliases:['ענבים']},
      {id:'watermelon', name:'بطيخ', emoji:'🍉', aliases:['אבטיח']},
      {id:'melon', name:'شمام', emoji:'🍈', aliases:['מלון']},
      {id:'strawberry', name:'فراولة', emoji:'🍓', aliases:['תות']},
      {id:'cherry', name:'كرز', emoji:'🍒', aliases:['דובדבן']},
      {id:'blueberry', name:'توت أزرق', emoji:'🫐', aliases:['אוכמניות']},
      {id:'avocado', name:'أفوكادو', emoji:'🥑', aliases:['אבוקדו']},
      {id:'mango', name:'مانجو', emoji:'🥭', aliases:['מנגו']},
      {id:'pear', name:'كمثرى', emoji:'🍐', aliases:['إجاص','אגס']},
      {id:'peach', name:'خوخ', emoji:'🍑', aliases:['אפרסק']},
      {id:'apricot', name:'مشمش', emoji:'🍑', aliases:['משמש']},
      {id:'kiwi', name:'كيوي', emoji:'🥝', aliases:['קיווי']},
      {id:'pineapple', name:'أناناس', emoji:'🍍', aliases:['אננס']},
      {id:'guava', name:'جوافة', emoji:'🍈', aliases:['גויאבה']},
      {id:'coconut', name:'جوز هند', emoji:'🥥', aliases:['קוקוס']},
      {id:'ginger', name:'زنجبيل', emoji:'🫚', aliases:["ג'ינג'ר"]},
      {id:'sweetpotato', name:'بطاطا حلوة', emoji:'🍠', aliases:['בטטה']},
      {id:'cabbage', name:'ملفوف', emoji:'🥬', aliases:['كرنب','כרוב']},
      {id:'cauliflower', name:'قرنبيط', emoji:'🥦', aliases:['כרובית']},
      {id:'broccoli', name:'بروكلي', emoji:'🥦', aliases:['ברוקולי']},
      {id:'mushroom', name:'فطر', emoji:'🍄', aliases:['פטריות']},
      {id:'corn', name:'ذرة', emoji:'🌽', aliases:['תירס']},
      {id:'radish', name:'فجل', emoji:'🌱', aliases:['צנון']},
      {id:'beet', name:'شمندر', emoji:'🫜', aliases:['סלק']},
      {id:'turnip', name:'لفت', emoji:'🥔', aliases:['לפת']},
      {id:'butternut', name:'قرع عسلي', emoji:'🎃', aliases:['דלעת']},
      {id:'pumpkin', name:'قرع', emoji:'🎃', aliases:['يقطين','דלעת']},
      {id:'asparagus', name:'هليون', emoji:'🌱', aliases:['אספרגוס']},
      {id:'artichoke', name:'أرضي شوكي', emoji:'🌿', aliases:['ארטישוק']},
      {id:'okra', name:'بامية', emoji:'🫛', aliases:['במיה']},
      {id:'fava', name:'فول أخضر', emoji:'🫘', aliases:['פול']},
      {id:'freshpeas', name:'بازيلاء طازجة', emoji:'🫛', aliases:['אפונה']},
      {id:'greenbeans', name:'فاصولياء خضراء', emoji:'🫘', aliases:['שעועית ירוקה']},
      {id:'pomegranate', name:'رمان', emoji:'🍎', aliases:['רימון']},
      {id:'dates', name:'تمر', emoji:'🌴', aliases:['תמרים']},
      {id:'figs', name:'تين', emoji:'🫐', aliases:['תאנים']},
      {id:'redonion', name:'بصل أحمر', emoji:'🧅', aliases:['בצל סגול']},
      {id:'icelettuce', name:'خس أيسبرغ', emoji:'🥬', aliases:['חסה אייסברג']},
      {id:'redcabbage', name:'ملفوف أحمر', emoji:'🥬', aliases:['כרוב סגול']},
      {id:'brusselsprouts', name:'كرنب بروكسل', emoji:'🥬', aliases:['כרוב ניצנים']},
      {id:'blackeyedpeas', name:'لوبيا طازجة', emoji:'🫛', aliases:['לוביה']},
      {id:'oystermushroom', name:'فطر محاري', emoji:'🍄', aliases:['פטריות צדפה']},
      {id:'cherrytomato', name:'بندورة كرزية', emoji:'🍅', aliases:['עגבניות שרי']},
      {id:'pomelo', name:'بوملي', emoji:'🍈', aliases:['פומלה']},
      {id:'nectarine', name:'خوخ نكتارين', emoji:'🍑', aliases:['נקטרינה']},
      {id:'plum', name:'برقوق', emoji:'🍑', aliases:['שזיף']},
      {id:'raspberry', name:'توت العليق', emoji:'🫐', aliases:['פטל']},
      {id:'chives', name:'ثوم معمر', emoji:'🌿', aliases:['עירית']}
    ]},
    {id:'dairy', name:'ألبان وبيض ومبردات', emoji:'🧀', items:[
      {id:'milk', name:'حليب', emoji:'🥛', aliases:['תנובה','טרה','חלב','Tnuva','تنوفا']},
      {id:'soymilk', name:'حليب صويا', emoji:'🥛', aliases:['חלב סויה']},
      {id:'almondmilk', name:'حليب لوز', emoji:'🥛', aliases:['חלב שקדים']},
      {id:'eggs', name:'بيض', emoji:'🥚', aliases:['ביצים']},
      {id:'whitecheese', name:'جبنة بيضاء', emoji:'🧀', aliases:['תנובה','גבינה לבנה','Tnuva','تنوفا']},
      {id:'yellowcheese', name:'جبنة صفراء', emoji:'🧀', aliases:['עמק','גבינה צהובה','Emek','عيمق']},
      {id:'halloumi', name:'حلوم', emoji:'🧀', aliases:['חלומי']},
      {id:'mozzarella', name:'موزاريلا', emoji:'🧀', aliases:['מוצרלה']},
      {id:'parmesan', name:'بارميزان', emoji:'🧀', aliases:['פרמזן']},
      {id:'cottagecheese', name:'جبنة قريش', emoji:'🧀', aliases:['גד',"קוטג'",'Gad','غاد']},
      {id:'creamcheese', name:'جبنة كريمة', emoji:'🧀', aliases:['גבינת שמנת']},
      {id:'yogurt', name:'لبن زبادي', emoji:'🥣', aliases:['لبن','יופלה','יוגורט','Yoplait','يوبليه']},
      {id:'greekyogurt', name:'زبادي يوناني', emoji:'🥣', aliases:['יוגורט יווני']},
      {id:'labneh', name:'لبنة', emoji:'🥣', aliases:['לבנה']},
      {id:'butter', name:'زبدة', emoji:'🧈', aliases:['תנובה','חמאה','Tnuva','تنوفا']},
      {id:'margarine', name:'مارجرين', emoji:'🧈', aliases:['מרגרינה','לינור','Linor','لينور']},
      {id:'cream', name:'قشطة', emoji:'🥛', aliases:['שמנת']},
      {id:'cookingcream', name:'كريمة طبخ', emoji:'🥛', aliases:['שמנת לבישול']},
      {id:'whippedcream', name:'كريمة مخفوقة', emoji:'🍦', aliases:['קצפת']},
      {id:'sourcream', name:'كريمة حامضة', emoji:'🥣', aliases:['سميتانة','שמנת חמוצה']},
      {id:'hummus', name:'حمص (معجون)', emoji:'🥣', aliases:['אחלה','חומוס']},
      {id:'babaganoush', name:'متبل', emoji:'🍆', aliases:['بابا غنوج','בבא גנוש']},
      {id:'olivesfresh', name:'زيتون', emoji:'🫒', aliases:['זיתים']},
      {id:'pickles', name:'مخلل', emoji:'🥒', aliases:['חמוצים']},
      {id:'tofu', name:'توفو', emoji:'⬜', aliases:['טופו']},
      {id:'feta', name:'جبنة فيتا', emoji:'🧀', aliases:['פטה','Feta']},
      {id:'edam', name:'جبنة إيدام', emoji:'🧀', aliases:['אדם']},
      {id:'gouda', name:'جبنة جودة', emoji:'🧀', aliases:['גאודה']},
      {id:'ricotta', name:'جبنة ريكوتا', emoji:'🧀', aliases:['ריקוטה']},
      {id:'buttermilk', name:'لبن رائب', emoji:'🥛', aliases:['חלב חמוץ','בטרמילק']},
      {id:'kefir', name:'كفير', emoji:'🥛', aliases:['קפיר']},
      {id:'pudding', name:'بودينغ', emoji:'🍮', aliases:['פודינג','מוס']},
      {id:'veganchees', name:'جبنة نباتية', emoji:'🧀', aliases:['תחליף גבינה','גבינה טבעונית']},
      {id:'vegancream', name:'كريمة نباتية', emoji:'🥛', aliases:['שמנת טבעונית']}
    ]},
    {id:'bakery', name:'خبز ومخبوزات', emoji:'🥖', items:[
      {id:'pita', name:'خبز عربي', emoji:'🫓', aliases:['خبز','كماج','פיתה']},
      {id:'wholewheatbread', name:'خبز أسمر', emoji:'🍞', aliases:['خبز كامل','לחם מלא']},
      {id:'baguette', name:'باغيت', emoji:'🥖', aliases:['באגט']},
      {id:'slicedbread', name:'خبز توست', emoji:'🍞', aliases:['לחם קצוץ']},
      {id:'buns', name:'خبز برجر', emoji:'🍞', aliases:['كيزر','לחמניות']},
      {id:'bagel', name:'بيغل', emoji:'🥯', aliases:['בייגל']},
      {id:'croissant', name:'كرواسون', emoji:'🥐', aliases:['קרואסון']},
      {id:'cake', name:'كيك', emoji:'🍰', aliases:['עוגה']},
      {id:'pastry', name:'معجنات', emoji:'🥐', aliases:['מאפה']},
      {id:'lafa', name:'لفة', emoji:'🫓', aliases:['לאפה']},
      {id:'lavash', name:'لواش', emoji:'🫓', aliases:['לאבש']},
      {id:'kaak', name:'كعك', emoji:'🥯', aliases:['כעכ']},
      {id:'donut', name:'دونات', emoji:'🍩', aliases:['סופגניה']},
      {id:'muffin', name:'مافن', emoji:'🧁', aliases:['מאפין']},
      {id:'rusks', name:'بقسماط', emoji:'🍪', aliases:['צנימים']},
      {id:'whitebread', name:'خبز أبيض', emoji:'🍞', aliases:['לחם לבן']},
      {id:'glutenfreebread', name:'خبز خالي من الغلوتين', emoji:'🍞', aliases:['לחם ללא גלוטן']},
      {id:'sajbread', name:'خبز صاج', emoji:'🫓', aliases:["פיתה סאג'"]},
      {id:'pizzadough', name:'عجينة بيتزا طازجة', emoji:'🍕', aliases:['בצק לפיצה']},
      {id:'pretzel', name:'بريتزل', emoji:'🥨', aliases:['פרצל']},
      {id:'cinnamonroll', name:'رول قرفة', emoji:'🥐', aliases:['רול קינמון']}
    ]},
    {id:'meat', name:'لحوم ودواجن وأسماك', emoji:'🍗', items:[
      {id:'chickenbreast', name:'صدور دجاج', emoji:'🍗', aliases:['חזה עוף']},
      {id:'chickenthighs', name:'أفخاذ دجاج', emoji:'🍗', aliases:['שוקי עוף']},
      {id:'chickenwings', name:'أجنحة دجاج', emoji:'🍗', aliases:['כנפיים']},
      {id:'chickenliver', name:'كبدة دجاج', emoji:'🍗', aliases:['כבד עוף']},
      {id:'groundchicken', name:'دجاج مفروم', emoji:'🍗', aliases:['עוף טחון']},
      {id:'wholechicken', name:'دجاجة كاملة', emoji:'🍗', aliases:['فروج','עוף שלם']},
      {id:'schnitzel', name:'شنيتسل', emoji:'🍗', aliases:['שניצל']},
      {id:'nuggets', name:'ناغتس دجاج', emoji:'🍗', aliases:['נאגטס']},
      {id:'turkey', name:'ديك رومي', emoji:'🦃', aliases:['הודו']},
      {id:'turkeythighs', name:'أفخاذ ديك رومي', emoji:'🦃', aliases:['שוקי הודו']},
      {id:'groundturkey', name:'لحمة ديك رومي مفرومة', emoji:'🦃', aliases:['הודו טחון']},
      {id:'groundbeef', name:'لحمة مفرومة', emoji:'🥩', aliases:['בשר טחון']},
      {id:'steak', name:'ستيك', emoji:'🥩', aliases:['סטייק']},
      {id:'stewbeef', name:'لحم بقر للطبخ', emoji:'🥩', aliases:['בשר לתבשיל']},
      {id:'beefliver', name:'كبدة بقر', emoji:'🥩', aliases:['כבד בקר']},
      {id:'veal', name:'لحم عجل', emoji:'🥩', aliases:['עגל']},
      {id:'beefpatty', name:'برجر لحم', emoji:'🍔', aliases:['המבורגר']},
      {id:'lamb', name:'لحم غنم', emoji:'🥩', aliases:['خروف','כבש']},
      {id:'lambchops', name:'ريش غنم', emoji:'🍖', aliases:['צלעות כבש']},
      {id:'kebab', name:'كباب', emoji:'🍢', aliases:['קבב']},
      {id:'shawarma', name:'شاورما', emoji:'🌯', aliases:['שווארמה']},
      {id:'sausage', name:'نقانق', emoji:'🌭', aliases:['سجق','נקניקיות']},
      {id:'chickensausage', name:'نقانق دجاج', emoji:'🌭', aliases:['נקניקיות עוף']},
      {id:'mortadella', name:'مرتديلا', emoji:'🥓', aliases:['מורטדלה']},
      {id:'salami', name:'سلامي', emoji:'🥓', aliases:['סלמי']},
      {id:'pastrami', name:'باسطرمة', emoji:'🥓', aliases:['פסטרמה']},
      {id:'luncheonmeat', name:'لانشون', emoji:'🥓', aliases:['נקניק']},
      {id:'fish', name:'سمك', emoji:'🐟', aliases:['דג']},
      {id:'salmon', name:'سلمون', emoji:'🐟', aliases:['סלמון']},
      {id:'tuna', name:'تونة', emoji:'🐟', aliases:['טונה']},
      {id:'solefish', name:'سمك موسى', emoji:'🐟', aliases:['משה רבנו']},
      {id:'denisfish', name:'سمك دنيس', emoji:'🐟', aliases:['דניס']},
      {id:'sardines', name:'سردين', emoji:'🐟', aliases:['סרדינים']},
      {id:'shrimp', name:'جمبري', emoji:'🍤', aliases:['قريدس','שרימפס']},
      {id:'calamari', name:'كاليماري', emoji:'🦑', aliases:['حبار','קלמארי']},
      {id:'smokedsalmon', name:'سلمون مدخن', emoji:'🐟', aliases:['סלמון מעושן']},
      {id:'bacon', name:'لحم مقدد', emoji:'🥓', aliases:['בייקון']},
      {id:'tilapia', name:'سمك بلطي', emoji:'🐟', aliases:['אמנון']}
    ]},
    {id:'frozen', name:'مجمدات', emoji:'🧊', items:[
      {id:'frozenveg', name:'خضار مجمدة', emoji:'🧊', aliases:['ירקות קפואים']},
      {id:'frozenspinach', name:'سبانخ مجمدة', emoji:'🧊', aliases:['תרד קפוא']},
      {id:'frozenpeas', name:'بازيلاء مجمدة', emoji:'🫛', aliases:['אפונה קפואה']},
      {id:'frozenfries', name:'بطاطا مقلية مجمدة', emoji:'🍟', aliases:["צ'יפס קפוא"]},
      {id:'icecream', name:'آيس كريم', emoji:'🍨', aliases:['بوظة','גלידה']},
      {id:'icecreamcones', name:'بسكوت بوظة', emoji:'🍦', aliases:['أقماع وكؤوس وافل للآيس كريم','كوني آيس كريم','גביעי גלידה','גביעי ופל לגלידה']},
      {id:'icecreamcake', name:'كيكة آيس كريم', emoji:'🎂', aliases:['عوجة جليدة','עוגת גלידה']},
      {id:'icecreamsandwich', name:'ساندويتش آيس كريم', emoji:'🍨', aliases:["סנדוויץ' גלידה"]},
      {id:'frozenpizza', name:'بيتزا مجمدة', emoji:'🍕', aliases:['פיצה קפואה']},
      {id:'frozenfish', name:'سمك مجمد', emoji:'🐟', aliases:['דג קפוא']},
      {id:'frozendough', name:'عجين مجمد', emoji:'🥟', aliases:['בצק קפוא']},
      {id:'frozenburger', name:'برجر مجمد', emoji:'🍔', aliases:['המבורגר קפוא']},
      {id:'nuggetsfrozen', name:'ناغتس مجمد', emoji:'🍗', aliases:['נאגטס קפוא']},
      {id:'waffles', name:'وافل', emoji:'🧇', aliases:['וופלים']},
      {id:'frozenfruit', name:'فواكه مجمدة', emoji:'🍓', aliases:['פירות קפואים']},
      {id:'veggieburger', name:'برغر نباتي مجمد', emoji:'🍔', aliases:['המבורגר צמחוני']},
      {id:'frozensamosa', name:'سمبوسة مجمدة', emoji:'🥟', aliases:['סמבוסק קפוא']},
      {id:'frozenmeatballs', name:'كرات لحم مجمدة', emoji:'🍖', aliases:['קציצות קפואות']},
      {id:'frozenshrimp', name:'جمبري مجمد', emoji:'🍤', aliases:['שרימפס קפוא']},
      {id:'edamame', name:'فول إدامامي مجمد', emoji:'🫛', aliases:['אדממה']},
      {id:'popsicle', name:'بوظة على عصا', emoji:'🍦', aliases:['ארטיק']}
    ]},
    {id:'pantry', name:'معلبات وحبوب وجاف', emoji:'🌾', items:[
      {id:'rice', name:'أرز', emoji:'🍚', aliases:['סוגת','אורז']},
      {id:'bulgur', name:'برغل', emoji:'🌾', aliases:['בורגול']},
      {id:'freekeh', name:'فريكة', emoji:'🌾', aliases:['פריכה']},
      {id:'couscous', name:'كسكس', emoji:'🌾', aliases:['קוסקוס']},
      {id:'vermicelli', name:'شعيرية', emoji:'🍜', aliases:['אטריות']},
      {id:'pasta', name:'معكرونة', emoji:'🍝', aliases:['باستا','אוסם','פסטה']},
      {id:'pastasauce', name:'صلصة باستا', emoji:'🥫', aliases:['אוסם','רוטב פסטה']},
      {id:'lentils', name:'عدس', emoji:'🫘', aliases:['עדשים']},
      {id:'redlentils', name:'عدس أحمر', emoji:'🫘', aliases:['עדשים אדומות']},
      {id:'chickpeasdry', name:'حمص جاف', emoji:'🫘', aliases:['חומוס יבש']},
      {id:'cannedchickpeas', name:'حمص معلب', emoji:'🥫', aliases:['גרגירי חומוס','גרגירי חומוס משומרים']},
      {id:'whitebeans', name:'فاصولياء بيضاء جافة', emoji:'🫘', aliases:['שעועית לבנה']},
      {id:'kidneybeans', name:'فاصولياء حمراء جافة', emoji:'🫘', aliases:['לוביה אדומה','שעועית אדומה']},
      {id:'blackbeans', name:'فاصولياء سوداء جافة', emoji:'🫘', aliases:['שעועית שחורה']},
      {id:'pintobeans', name:'فاصولياء منقطة (بينتو)', emoji:'🫘', aliases:['שעועית מנומרת','שעועית פינטו']},
      {id:'limabeans', name:'فاصولياء ليما', emoji:'🫘', aliases:['بوبس','שעועית לימה','שעועית בובס']},
      {id:'adzukibeans', name:'فاصولياء أدزوكي', emoji:'🫘', aliases:['أزوكي','שעועית אזוקי']},
      {id:'driedblackeyedpeas', name:'لوبيا جافة', emoji:'🫘', aliases:['לוביה יבשה']},
      {id:'greensplitpeas', name:'بازلاء خضراء مجففة مقسمة', emoji:'🫛', aliases:['אפונה ירוקה מפוצלת']},
      {id:'yellowsplitpeas', name:'بازلاء صفراء مجففة مقسمة', emoji:'🫛', aliases:['אפונה צהובה מפוצלת']},
      {id:'driedfava', name:'فول جاف كامل', emoji:'🫘', aliases:['פול יבש']},
      {id:'splitfava', name:'فول مقشور مجروش', emoji:'🫘', aliases:['فول مقشور','פול מקולף']},
      {id:'soybeans', name:'فول الصويا', emoji:'🫘', aliases:['פולי סויה']},
      {id:'mungbeans', name:'فول الماش', emoji:'🫘', aliases:['ماش','שעועית מש']},
      {id:'lupini', name:'ترمس', emoji:'🫘', aliases:['תורמוס']},
      {id:'favacanned', name:'فول مدمس', emoji:'🥫', aliases:['פול']},
      {id:'cannedtuna', name:'تونة معلبة', emoji:'🥫', aliases:['טונה בשימורים']},
      {id:'cannedcorn', name:'ذرة معلبة', emoji:'🥫', aliases:['תירס משומר']},
      {id:'tomatopaste', name:'معجون طماطم', emoji:'🥫', aliases:['رب بندورة','אוסם','רסק עגבניות']},
      {id:'cannedbeans', name:'فاصولياء معلبة', emoji:'🥫', aliases:['שעועית משומרת']},
      {id:'flour', name:'طحين', emoji:'🌾', aliases:['دقيق','קמח']},
      {id:'sugar', name:'سكر', emoji:'🧂', aliases:['סוכר']},
      {id:'oats', name:'شوفان', emoji:'🥣', aliases:['שיבולת שועל']},
      {id:'cereal', name:'كورن فليكس', emoji:'🥣', aliases:['حبوب فطور','דגני בוקר']},
      {id:'oliveoil', name:'زيت زيتون', emoji:'🫒', aliases:['שמן זית']},
      {id:'sunfloweroil', name:'زيت دوار الشمس', emoji:'🛢️', aliases:['שמן חמניות']},
      {id:'vinegar', name:'خل', emoji:'🍶', aliases:['חומץ']},
      {id:'honey', name:'عسل', emoji:'🍯', aliases:['דבש']},
      {id:'tahini', name:'طحينة', emoji:'🥣', aliases:['טחינה']},
      {id:'yeast', name:'خميرة', emoji:'🍞', aliases:['שמרים']},
      {id:'bakingpowder', name:'بيكنغ باودر', emoji:'🧂', aliases:['אבקת אפייה']},
      {id:'cornstarch', name:'نشا', emoji:'🧂', aliases:['עמילן תירס']},
      {id:'vanilla', name:'فانيلا', emoji:'🧂', aliases:['וניל']},
      {id:'cocoa', name:'كاكاو', emoji:'🍫', aliases:['קקאו']},
      {id:'chocolatesyrup', name:'سيروب شوكولاتة', emoji:'🍫', aliases:['صوص شوكولاتة','סירופ שוקולד']},
      {id:'sprinkles', name:'رشات ملونة للتزيين', emoji:'🎊', aliases:['زينة حلويات','סוכריות קישוט']},
      {id:'cornoil', name:'زيت ذرة', emoji:'🌽', aliases:['שמן תירס']},
      {id:'canolaoil', name:'زيت كانولا', emoji:'🫒', aliases:['שמן קנולה']},
      {id:'applecidervinegar', name:'خل تفاح', emoji:'🍎', aliases:['חומץ תפוחים']},
      {id:'bbqsauce', name:'صلصة باربكيو', emoji:'🍖', aliases:['רוטב ברביקיו']},
      {id:'pomegranatemolasses', name:'دبس رمان', emoji:'🍈', aliases:['דבש רימונים']},
      {id:'silan', name:'دبس تمر', emoji:'🍯', aliases:['سيلان','סילאן','Silan']},
      {id:'jam', name:'مربى', emoji:'🍓', aliases:['ריבה']},
      {id:'chocospread', name:'شوكولاتة للدهن', emoji:'🍫', aliases:['נוטלה','Nutella']},
      {id:'peanutbutter', name:'زبدة فول سوداني', emoji:'🥜', aliases:['חמאת בוטנים']},
      {id:'condensedmilk', name:'حليب مكثف محلى', emoji:'🥫', aliases:['חלב מרוכז']},
      {id:'powderedmilk', name:'حليب بودرة', emoji:'🥛', aliases:['אבקת חלב']},
      {id:'basmatirice', name:'أرز بسمتي', emoji:'🍚', aliases:['אורז בסמטי']},
      {id:'yellowlentils', name:'عدس أصفر', emoji:'🫘', aliases:['עדשים צהובות']},
      {id:'cannedtomatoes', name:'طماطم مقشرة معلبة', emoji:'🥫', aliases:['עגבניות מקולפות']},
      {id:'cannedolives', name:'زيتون معلب', emoji:'🫒', aliases:['זיתים בקופסה']},
      {id:'cannedsardines', name:'سردين معلب', emoji:'🐟', aliases:['סרדינים בקופסה']}
    ]},
    {id:'spices', name:'بهارات وصلصات', emoji:'🧂', items:[
      {id:'blackpepper', name:'فلفل أسود', emoji:'🧂', aliases:['פלפל שחור']},
      {id:'whitepepper', name:'فلفل أبيض', emoji:'🧂', aliases:['פלפל לבן']},
      {id:'cumin', name:'كمون', emoji:'🧂', aliases:['כמון']},
      {id:'sumac', name:'سماق', emoji:'🧂', aliases:['סומק']},
      {id:'zaatar', name:'زعتر', emoji:'🌿', aliases:['זעתר']},
      {id:'cinnamon', name:'قرفة', emoji:'🧂', aliases:['קינמון']},
      {id:'cardamom', name:'هيل', emoji:'🧂', aliases:['הל']},
      {id:'cloves', name:'قرنفل', emoji:'🧂', aliases:['ציפורן']},
      {id:'anise', name:'يانسون', emoji:'🧂', aliases:['אניס']},
      {id:'nigella', name:'حبة سوداء', emoji:'🧂', aliases:['קצח']},
      {id:'allspice', name:'بهار حلو', emoji:'🧂', aliases:['פימנטו']},
      {id:'turmeric', name:'كركم', emoji:'🧂', aliases:['כורכום']},
      {id:'paprika', name:'بابريكا', emoji:'🧂', aliases:['פפריקה']},
      {id:'baharat', name:'بهارات مشكلة', emoji:'🧂', aliases:['בהרט']},
      {id:'salt', name:'ملح', emoji:'🧂', aliases:['מלח']},
      {id:'ketchup', name:'كاتشب', emoji:'🍅', aliases:['קטשופ']},
      {id:'mayo', name:'مايونيز', emoji:'🥣', aliases:['מיונז']},
      {id:'mustard', name:'خردل', emoji:'🥣', aliases:['חרדל']},
      {id:'soysauce', name:'صلصة الصويا', emoji:'🥣', aliases:['רוטב סויה']},
      {id:'hotsauce', name:'صلصة حارة', emoji:'🌶️', aliases:['רוטב חריף']},
      {id:'bouillon', name:'مرقة مكعبات', emoji:'🧂', aliases:['كنور','אבקת מרק']},
      {id:'garlicpowder', name:'مسحوق ثوم', emoji:'🧂', aliases:['אבקת שום']},
      {id:'onionpowder', name:'مسحوق بصل', emoji:'🧂', aliases:['אבקת בצל']},
      {id:'oregano', name:'أوريغانو', emoji:'🌿', aliases:['אורגנו']},
      {id:'driedbasil', name:'ريحان مجفف', emoji:'🌿', aliases:['בזיליקום יבש']},
      {id:'rosemary', name:'إكليل الجبل', emoji:'🌿', aliases:['רוזמרין']},
      {id:'groundcoriander', name:'كزبرة مطحونة', emoji:'🧂', aliases:['כוסברה טחונה']},
      {id:'chiliflakes', name:'شطة مطحونة', emoji:'🌶️', aliases:["פלפל צ'ילי גרוס"]}
    ]},
    {id:'drinks', name:'مشروبات', emoji:'🥤', items:[
      {id:'water', name:'مياه', emoji:'💧', aliases:['נביעות','מי עדן','מים','Neviot','Mei Eden','نبيعوت','مي عيدن']},
      {id:'sparklingwater', name:'مياه غازية', emoji:'🫧', aliases:['מים מוגזים']},
      {id:'juice', name:'عصير', emoji:'🧃', aliases:['פריגת','מיץ','Prigat','بريغات']},
      {id:'soda', name:'كولا', emoji:'🥤', aliases:['صودا','קוקה קולה','פפסי','קולה','Coca-Cola','Pepsi','كوكا كولا','بيبسي']},
      {id:'coffee', name:'قهوة', emoji:'☕', aliases:['עלית','קפה']},
      {id:'turkishcoffee', name:'قهوة تركية', emoji:'☕', aliases:['עלית','קפה טורקי']},
      {id:'instantcoffee', name:'نسكافيه', emoji:'☕', aliases:['Nescafe','נמס']},
      {id:'tea', name:'شاي', emoji:'🍵', aliases:['ויסוצקי','תה','Wissotzky','ويسوتسكي']},
      {id:'greentea', name:'شاي أخضر', emoji:'🍵', aliases:['תה ירוק']},
      {id:'energydrink', name:'مشروب طاقة', emoji:'⚡', aliases:['משקה אנרגיה']},
      {id:'sportsdrink', name:'مشروب رياضي', emoji:'🥤', aliases:['איזוטוני']},
      {id:'maltdrink', name:'مشروب مالت', emoji:'🍺', aliases:['מאלט']},
      {id:'beer', name:'بيرة', emoji:'🍺', aliases:['בירה']},
      {id:'wine', name:'نبيذ', emoji:'🍷', aliases:['יין']},
      {id:'lemonade', name:'ليموناضة', emoji:'🍋', aliases:['לימונדה']},
      {id:'chocmilk', name:'شوكولاطة حليب', emoji:'🍫', aliases:['שוקו']},
      {id:'mineralwater', name:'مياه معدنية', emoji:'💧', aliases:['מי מעיינות']},
      {id:'freshorangejuice', name:'عصير برتقال طازج', emoji:'🍊', aliases:['מיץ תפוזים טרי']},
      {id:'oatmilk', name:'حليب الشوفان', emoji:'🥛', aliases:['חלב שיבולת שועל']},
      {id:'arabiccoffee', name:'قهوة عربية', emoji:'☕', aliases:['קפה ערבי']},
      {id:'mintea', name:'شاي بالنعناع', emoji:'🍵', aliases:['תה נענע']}
    ]},
    {id:'snacks', name:'وجبات خفيفة وحلويات', emoji:'🍫', items:[
      {id:'chips', name:'تشيبس', emoji:'🍟', aliases:['شيبس',"צ'יפס"]},
      {id:'cornchips', name:'رقائق ذرة', emoji:'🌽', aliases:["צ'יטוס",'Cheetos','تشيتوس']},
      {id:'crackers', name:'بسكويت مالح', emoji:'🍘', aliases:['קרקרים']},
      {id:'chocolate', name:'شوكولاطة', emoji:'🍫', aliases:['שוקולד','עלית','Elite','إيليت']},
      {id:'cookies', name:'بسكويت', emoji:'🍪', aliases:['עוגיות','אוראו','Oreo','أوريو']},
      {id:'wafer', name:'ويفر', emoji:'🍫', aliases:['וופל']},
      {id:'nuts', name:'مكسرات', emoji:'🥜', aliases:['אגוזים']},
      {id:'almonds', name:'لوز', emoji:'🌰', aliases:['שקדים']},
      {id:'walnuts', name:'جوز', emoji:'🌰', aliases:['אגוזי מלך']},
      {id:'pistachios', name:'فستق حلبي', emoji:'🌰', aliases:['فستق','פיסטוק']},
      {id:'hazelnuts', name:'بندق', emoji:'🌰', aliases:['אגוזי לוז']},
      {id:'pecans', name:'بيكان', emoji:'🌰', aliases:['פקאן']},
      {id:'macadamia', name:'مكاداميا', emoji:'🌰', aliases:['מקדמיה']},
      {id:'brazilnuts', name:'جوز برازيلي', emoji:'🌰', aliases:['אגוזי ברזיל']},
      {id:'pinenuts', name:'صنوبر', emoji:'🌰', aliases:['צנוברים']},
      {id:'chestnuts', name:'كستناء', emoji:'🌰', aliases:['ערמונים']},
      {id:'seeds', name:'بذور', emoji:'🌻', aliases:['لب','גרעינים']},
      {id:'sunflowerseeds', name:'بذر عباد الشمس (لب أبيض)', emoji:'🌻', aliases:['לב לבן','גרעיני חמניה']},
      {id:'pumpkinseeds', name:'بذر اليقطين', emoji:'🎃', aliases:['לב','גרעיני דלעת']},
      {id:'watermelonseeds', name:'بذر البطيخ (لب أسود)', emoji:'🍉', aliases:['לב שחור','גרעיני אבטיח']},
      {id:'sesameseeds', name:'سمسم', emoji:'🌱', aliases:['שומשום']},
      {id:'chiaseeds', name:'بذور الشيا', emoji:'🌱', aliases:["זרעי צ'יה"]},
      {id:'flaxseeds', name:'بذور الكتان', emoji:'🌱', aliases:['זרעי פשתן']},
      {id:'poppyseeds', name:'بذور الخشخاش', emoji:'🌱', aliases:['פרג']},
      {id:'raisins', name:'زبيب', emoji:'🍇', aliases:['צימוקים']},
      {id:'driedfruit', name:'فواكه مجففة', emoji:'🍇', aliases:['פירות יבשים']},
      {id:'candy', name:'حلوى', emoji:'🍬', aliases:['ממתקים']},
      {id:'gum', name:'علكة', emoji:'🍬', aliases:['מסטיק']},
      {id:'marshmallow', name:'مارشميلو', emoji:'🍡', aliases:['מרשמלו']},
      {id:'popcorn', name:'فشار', emoji:'🍿', aliases:['פופקורן']},
      {id:'halva', name:'حلاوة', emoji:'🍯', aliases:['חלווה']},
      {id:'granolabar', name:'غرانولا', emoji:'🍫', aliases:['גרנולה']},
      {id:'proteinbar', name:'بروتين بار', emoji:'🍫', aliases:['חטיף חלבון']},
      {id:'cashews', name:'كاجو', emoji:'🥜', aliases:['קשיו']},
      {id:'peanuts', name:'فول سوداني محمص', emoji:'🥜', aliases:['בוטנים']},
      {id:'baklava', name:'بقلاوة', emoji:'🥮', aliases:['בקלאווה']},
      {id:'kanafeh', name:'كنافة', emoji:'🧡', aliases:['כנאפה']}
    ]},
    {id:'cleaning', name:'منظفات ومستلزمات المنزل', emoji:'🧽', items:[
      {id:'dishsoap', name:'صابون صحون', emoji:'🧴', aliases:['صبونة جلي','פיירי','סבון כלים','Fairy','فيري','פלמוליב','Palmolive','بالمولايف','פריל','Pril','بريل']},
      {id:'handsoap', name:'صابون يدين سائل', emoji:'🧴', aliases:['סבון ידיים נוזלי','דטול','Dettol','ديتول']},
      {id:'laundrydetergent', name:'مسحوق غسيل', emoji:'🧴', aliases:['بودرة غسيل','אריאל','פרסיל','אבקת כביסה','Ariel','Persil','أريل','بيرسيل','סנו','Sano','سانو']},
      {id:'softener', name:'منعم ملابس', emoji:'🧴', aliases:['קומפורט','מרכך כביסה','Comfort','كومفورت','לנור','Lenor','لينور']},
      {id:'bleach', name:'كلور', emoji:'🧴', aliases:['أكونوميكا','אקונומיקה','קלורוקס','Clorox','كلوروكس']},
      {id:'allpurposecleaner', name:'منظف متعدد الاستخدامات', emoji:'🧴', aliases:['סנו','Sano','سانو','מנקה רב שימושי','סיף','Cif','سيف','מר מאסל','Mr Muscle','مستر ماسل']},
      {id:'airfreshener', name:'معطر جو', emoji:'🌸', aliases:['مطيب جو','מרענן אוויר','גלייד','Glade','غلايد','אייר וויק','Air Wick','ايرويك','פבריז','Febreze','فيبريز']},
      {id:'insecticide', name:'مبيد حشرات', emoji:'🐜', aliases:['رشاش حشرات','רסס נגד חרקים','ראייד','Raid','رايد']},
      {id:'sponge', name:'إسفنجة', emoji:'🧽', aliases:['ספוג']},
      {id:'gloves', name:'قفازات تنظيف', emoji:'🧤', aliases:['قفازات مطبخ','כפפות ניקיון','כפפות ניטריל','נעל','nitrile']},
      {id:'laundryscentbeads', name:'كريات معطرة للغسيل', emoji:'💧', aliases:['פניני בישום לכביסה','Unstopables']},
      {id:'steelwool', name:'ليف حديد', emoji:'🧽', aliases:['ספוגיות פלדה','סקוצ']},
      {id:'superglue', name:'غراء لاصق قوي', emoji:'🧴', aliases:['דבק חזק','Super glue','سوبر غلو']},
      {id:'trashbags', name:'أكياس زبالة', emoji:'🗑️', aliases:['שקיות זבל']},
      {id:'foil', name:'ورق ألمنيوم', emoji:'🧻', aliases:['נייר כסף']},
      {id:'plasticwrap', name:'نايلون تغليف', emoji:'🧻', aliases:['ניילון נצמד']},
      {id:'papertowels', name:'مناديل مطبخ', emoji:'🧻', aliases:['מגבות נייר','מולט','Molett','موليت']},
      {id:'toiletpaper', name:'ورق تواليت', emoji:'🧻', aliases:['נייר טואלט','לילי','Lily','ليلي']},
      {id:'tissues', name:'مناديل ورقية', emoji:'🧻', aliases:['טישו','לילי','Lily','ليلي']},
      {id:'glasscleaner', name:'منظف زجاج', emoji:'🧴', aliases:['מנקה זכוכית','וינדקס','Windex','ويندكس']},
      {id:'freezerbags', name:'أكياس تجميد', emoji:'🧊', aliases:['שקיות הקפאה']},
      {id:'cleaningbrush', name:'فرشاة تنظيف', emoji:'🧽', aliases:['מברשת ניקוי']},
      {id:'ovencleaner', name:'منظف فرن', emoji:'🧴', aliases:['מנקה תנור']},
      {id:'toiletcleaner', name:'منظف مرحاض', emoji:'🧴', aliases:['מנקה אסלה','דומסטוס','Domestos','دومستوس','הארפיק','Harpic','هاربيك']},
      {id:'disinfectant', name:'معقم للأسطح', emoji:'🧴', aliases:['مطهر','דטול','Dettol','ديتول','מחטא משטחים']},
      {id:'stainremover', name:'مزيل بقع', emoji:'🧴', aliases:['ואניש','Vanish','فانيش']},
      {id:'dishwashertablets', name:'أقراص غسالة صحون', emoji:'🍽️', aliases:['פיניש','Finish','فينش','כדורי מדיח','קפסולות מדיח','קפסולות']},
      {id:'descaler', name:'مزيل ترسبات كلسية', emoji:'🧴', aliases:['مزيل أبنية','קלגון','Calgon','كالغون','מסיר אבנית']},
      {id:'draincleaner', name:'مفتح مجاري', emoji:'🚿', aliases:['מפתח סתימות']},
      {id:'moldremover', name:'مزيل عفن', emoji:'🧴', aliases:['מסיר עובש']},
      {id:'floorcleaner', name:'منظف أرضيات', emoji:'🧴', aliases:['נוזל לרצפות']},
      {id:'furniturepolish', name:'ملمع أثاث', emoji:'🪑', aliases:['מבריק רהיטים']},
      {id:'carpetcleaner', name:'منظف سجاد', emoji:'🧴', aliases:['מנקה שטיחים']},
      {id:'degreaser', name:'مزيل دهون', emoji:'🧴', aliases:['מסיר שומן']},
      {id:'dustcloth', name:'قطعة قماش تنظيف', emoji:'🧽', aliases:['ميكروفايبر','מטלית ניקוי','מיקרופייבר']},
      {id:'broom', name:'مكنسة', emoji:'🧹', aliases:['מטאטא']},
      {id:'mop', name:'ممسحة أرضيات', emoji:'🧹', aliases:['סחבה','מגב רצפה']},
      {id:'squeegee', name:'ممسحة زجاج', emoji:'🧹', aliases:['מגב חלונות']},
      {id:'dustpan', name:'جاروف زبالة', emoji:'🧹', aliases:['יעה']},
      {id:'bucket', name:'دلو', emoji:'🪣', aliases:['דלי']},
      {id:'mosquitorepellent', name:'طارد حشرات', emoji:'🦟', aliases:['طارد بعوض','דוחה יתושים']},
      {id:'cleaningwipes', name:'مناديل تنظيف الأسطح', emoji:'🧻', aliases:['מגבוני ניקוי']},
      {id:'shoepolish', name:'ملمع أحذية', emoji:'👞', aliases:['משחת נעליים']}
    ]},
    {id:'personal', name:'عناية شخصية', emoji:'🧴', items:[
      {id:'shampoo', name:'شامبو', emoji:'🧴', aliases:['שמפו']},
      {id:'soap', name:'صابون', emoji:'🧼', aliases:['סבון']},
      {id:'bodywash', name:'غسول جسم', emoji:'🧴', aliases:['סבון גוף']},
      {id:'toothpaste', name:'معجون أسنان', emoji:'🪥', aliases:['קולגייט','משחת שיניים','Colgate','كولجيت']},
      {id:'toothbrush', name:'فرشاة أسنان', emoji:'🪥', aliases:['מברשת שיניים']},
      {id:'deodorant', name:'مزيل عرق', emoji:'🧴', aliases:['דאודורנט']},
      {id:'sunscreen', name:'واقي شمس', emoji:'🧴', aliases:['קרם הגנה']},
      {id:'bandaids', name:'لصقات جروح', emoji:'🩹', aliases:['פלסטרים','Band-Aid']},
      {id:'pads', name:'فوط صحية', emoji:'🩹', aliases:['תחבושות']},
      {id:'razors', name:'شفرات حلاقة', emoji:'🪒', aliases:['סכיני גילוח','Gillette','جيليت']},
      {id:'handcream', name:'كريم يدين', emoji:'🧴', aliases:['קרם ידיים']},
      {id:'shavingcream', name:'معجون حلاقة', emoji:'🪒', aliases:['קצף גילוח']},
      {id:'perfume', name:'عطر', emoji:'🧴', aliases:['בושם']},
      {id:'hairbrush', name:'فرشاة شعر', emoji:'💇', aliases:['מברשת שיער']},
      {id:'comb', name:'مشط', emoji:'💇', aliases:['מסרק']},
      {id:'nailclipper', name:'قصافة أظافر', emoji:'💅', aliases:['גזזי ציפורניים']},
      {id:'cottonpads', name:'قطن طبي', emoji:'🧴', aliases:['פדי כותנה','צמר גפן']},
      {id:'cottonswabs', name:'أعواد قطنية', emoji:'🧴', aliases:['צמר גפן באוזניים','Q-tips']},
      {id:'bodylotion', name:'كريم مرطب للجسم', emoji:'🧴', aliases:['קרם גוף']},
      {id:'mouthwash', name:'غسول فم', emoji:'🦷', aliases:['מי פה']},
      {id:'dentalfloss', name:'خيط تنظيف الأسنان', emoji:'🦷', aliases:['חוט דנטלי']}
    ]},
    {id:'baby', name:'أطفال ورضع', emoji:'🍼', items:[
      {id:'diapers', name:'حفاضات', emoji:'👶', aliases:['האגיס','פמפרס','חיתולים','Huggies','Pampers','هاغيز','بامبرز']},
      {id:'wipes', name:'مناديل مبللة', emoji:'👶', aliases:['האגיס','מגבונים']},
      {id:'babyformula', name:'حليب أطفال', emoji:'🍼', aliases:['מטרנה','תרכובת תינוקות','Materna','ماترنا']},
      {id:'babypuree', name:'طعام أطفال معلب', emoji:'🍼', aliases:['מחית לתינוקות']},
      {id:'babycereal', name:'حبوب أطفال', emoji:'🍼', aliases:['דגני תינוקות']},
      {id:'babybottle', name:'رضاعة', emoji:'🍼', aliases:['בקבוק תינוקות']},
      {id:'pacifier', name:'لهاية', emoji:'🍼', aliases:['מוצץ']},
      {id:'diaperrashcream', name:'كريم للطفح الجلدي', emoji:'🍼', aliases:['משחה לפריחה']},
      {id:'babyshampoo', name:'شامبو أطفال', emoji:'🍼', aliases:['שמפו לתינוקות']},
      {id:'babyoil', name:'زيت أطفال', emoji:'🍼', aliases:['שמן לתינוקות']},
      {id:'babysoap', name:'صابون أطفال', emoji:'🍼', aliases:['סבון לתינוקות']}
    ]},
    {id:'pharmacy', name:'صيدلية وعناية صحية', emoji:'💊', items:[
      {id:'painreliever', name:'مسكن ألم', emoji:'💊', aliases:['אקמול','Acamol']},
      {id:'vitamins', name:'فيتامينات', emoji:'💊', aliases:['ויטמינים']},
      {id:'coldmedicine', name:'دواء برد', emoji:'💊', aliases:['תרופה להצטננות']},
      {id:'thermometer', name:'ميزان حرارة', emoji:'🌡️', aliases:['מדחום']},
      {id:'facemasks', name:'كمامات', emoji:'😷', aliases:['מסכות פנים']},
      {id:'handsanitizer', name:'معقم يدين', emoji:'🧴', aliases:["ג'ל חיטוי ידיים"]},
      {id:'antisepticwipes', name:'مناديل معقمة', emoji:'🧴', aliases:['מגבונים מחטאים']},
      {id:'eyedrops', name:'قطرة عين', emoji:'💧', aliases:['טיפות עיניים']},
      {id:'burnointment', name:'مرهم للحروق', emoji:'💊', aliases:['משחה לכוויות']},
      {id:'antacid', name:'أقراص للمعدة', emoji:'💊', aliases:['נוגד חומצה']}
    ]},
    {id:'household', name:'أدوات ومستلزمات منزلية', emoji:'🔋', items:[
      {id:'batteries', name:'بطاريات', emoji:'🔋', aliases:['סוללות']},
      {id:'lightbulbs', name:'مصابيح إضاءة', emoji:'💡', aliases:['נורות']},
      {id:'matches', name:'أعواد ثقاب وولاعة', emoji:'🔥', aliases:['גפרורים','מצית']},
      {id:'candles', name:'شموع', emoji:'🕯️', aliases:['נרות']},
      {id:'plasticcontainers', name:'حاويات بلاستيك', emoji:'🥡', aliases:['קופסאות פלסטיק']},
      {id:'papercups', name:'أكواب ورقية', emoji:'🥤', aliases:['כוסות נייר']},
      {id:'paperplates', name:'أطباق ورقية', emoji:'🍽️', aliases:['צלחות נייר']},
      {id:'plasticcutlery', name:'أدوات مائدة بلاستيك', emoji:'🍴', aliases:['סכו"ם חד פעמי']},
      {id:'napkins', name:'مناديل سفرة', emoji:'🧻', aliases:['מפיות']}
    ]},
    {id:'petcare', name:'حيوانات أليفة', emoji:'🐾', items:[
      {id:'catfood', name:'طعام قطط', emoji:'🐱', aliases:['אוכל לחתולים']},
      {id:'dogfood', name:'طعام كلاب', emoji:'🐶', aliases:['אוכל לכלבים']},
      {id:'catlitter', name:'رمل قطط', emoji:'🐱', aliases:['חול לחתולים']},
      {id:'pettreats', name:'حلويات حيوانات أليفة', emoji:'🐾', aliases:['חטיפים לחיות מחמד']}
    ]},
    {id:'kitchenware', name:'أواني وأدوات مطبخ', emoji:'🍳', items:[
      {id:'pot', name:'طنجرة', emoji:'🍲', aliases:['قدر','סיר']},
      {id:'pressurecooker', name:'قدر ضغط', emoji:'🍲', aliases:['סיר לחץ']},
      {id:'fryingpan', name:'مقلاية', emoji:'🍳', aliases:['مقلاي','طاسة','מחבת']},
      {id:'grillpan', name:'طاسة شواء', emoji:'🍳', aliases:['מחבת גריל']},
      {id:'wok', name:'ووك', emoji:'🥘', aliases:['וואק']},
      {id:'bakingtray', name:'صينية فرن', emoji:'🍞', aliases:['תבנית אפייה']},
      {id:'cakepan', name:'قالب كيك', emoji:'🎂', aliases:['תבנית עוגה','תבנית אינגליש קייק']},
      {id:'muffintray', name:'قالب مافن', emoji:'🧁', aliases:['תבנית מאפינס']},
      {id:'casserole', name:'طبق فرن', emoji:'🍲', aliases:['פירקס','תבנית זכוכית']},
      {id:'spoon', name:'معلقة', emoji:'🥄', aliases:['ملعقة','כף']},
      {id:'teaspoon', name:'معلقة صغيرة', emoji:'🥄', aliases:['ملعقة شاي','כפית']},
      {id:'tablespoon', name:'معلقة كبيرة', emoji:'🥄', aliases:['ملعقة أكل','כף גדולה']},
      {id:'fork', name:'شوكة', emoji:'🍴', aliases:['מזלג']},
      {id:'knife', name:'سكين', emoji:'🔪', aliases:['سكينة','סכין']},
      {id:'icecreamscoop', name:'معلقة بوظة', emoji:'🍨', aliases:['ملعقة آيس كريم','כף גלידה']},
      {id:'ladle', name:'مغرفة', emoji:'🥄', aliases:['כף מרק']},
      {id:'slottedspoon', name:'ملعقة مصفاة', emoji:'🥄', aliases:['כף מחוררת']},
      {id:'spatula', name:'ملعقة قلب', emoji:'🥄', aliases:['سباتولا','מרית']},
      {id:'whisk', name:'خفاقة', emoji:'🥄', aliases:['מקצף']},
      {id:'tongs', name:'ملقط مطبخ', emoji:'🥢', aliases:['מלקחיים']},
      {id:'peeler', name:'مقشرة', emoji:'🔪', aliases:['קולפן']},
      {id:'grater', name:'مبشرة', emoji:'🧀', aliases:['פומפייה','מגרדת']},
      {id:'canopener', name:'فتاحة علب', emoji:'🥫', aliases:['פותחן קופסאות']},
      {id:'bottleopener', name:'فتاحة زجاجات', emoji:'🍾', aliases:['פותחן בקבוקים']},
      {id:'corkscrew', name:'فتاحة نبيذ', emoji:'🍷', aliases:['חלץ פקקים']},
      {id:'kitchenscissors', name:'مقص مطبخ', emoji:'✂️', aliases:['מספריים למטבח']},
      {id:'rollingpin', name:'شوبك', emoji:'🥖', aliases:['نشابة','מערוך']},
      {id:'cuttingboard', name:'لوح تقطيع', emoji:'🪵', aliases:['קרש חיתוך']},
      {id:'mandoline', name:'مبشرة تقطيع (مندولين)', emoji:'🔪', aliases:['מנדולינה']},
      {id:'pitcher', name:'إبريق ماء', emoji:'🫗', aliases:['كنكة ماء','קנקן מים']},
      {id:'colander', name:'مصفاة', emoji:'🥗', aliases:['מסננת']},
      {id:'sieve', name:'منخل', emoji:'🥣', aliases:['غربال','מסננת קמח']},
      {id:'funnel', name:'قمع', emoji:'⏳', aliases:['משפך']},
      {id:'garlicpress', name:'كسارة ثوم', emoji:'🧄', aliases:['מכבש שום']},
      {id:'citrusjuicer', name:'عصارة ليمون', emoji:'🍋', aliases:['מסחטת לימון']},
      {id:'measuringcup', name:'كوب قياس', emoji:'🥤', aliases:['כוס מדידה']},
      {id:'measuringspoons', name:'ملاعق قياس', emoji:'🥄', aliases:['כפות מדידה']},
      {id:'kitchenscale', name:'ميزان مطبخ', emoji:'⚖️', aliases:['משקל מטבח']},
      {id:'mortar', name:'هاون', emoji:'🥣', aliases:['مدقة','מכתש ועלי']},
      {id:'skewers', name:'أسياخ شواء', emoji:'🍢', aliases:['שיפודים']},
      {id:'plate', name:'صحن', emoji:'🍽️', aliases:['طبق','צלחת']},
      {id:'bowl', name:'زبدية', emoji:'🥣', aliases:['وعاء','קערה']},
      {id:'cup', name:'كاسة', emoji:'🥤', aliases:['كوب','כוס']},
      {id:'mug', name:'كوب قهوة', emoji:'☕', aliases:['ماج','ספל']},
      {id:'servingtray', name:'صينية تقديم', emoji:'🍽️', aliases:['מגש הגשה']},
      {id:'teapot', name:'إبريق شاي', emoji:'🫖', aliases:['קומקום תה']},
      {id:'coffeepot', name:'دلة قهوة', emoji:'☕', aliases:['ركوة','קנקן קפה']},
      {id:'waterbottle', name:'قنينة ماء', emoji:'🍶', aliases:['בקבוק מים']},
      {id:'thermos', name:'ترمس', emoji:'🧴', aliases:['תרמוס']},
      {id:'kettle', name:'غلاية كهربائية', emoji:'♨️', aliases:['קומקום חשמלי']},
      {id:'toaster', name:'توستر', emoji:'🍞', aliases:['טוסטר']},
      {id:'blender', name:'خلاط', emoji:'🧃', aliases:['בלנדר']},
      {id:'handmixer', name:'خلاط يدوي', emoji:'🥣', aliases:['מיקסר יד']},
      {id:'foodprocessor', name:'محضرة طعام', emoji:'🍽️', aliases:['מעבד מזון']},
      {id:'electricjuicer', name:'عصارة كهربائية', emoji:'🍊', aliases:['מסחטת פירות חשמלית']},
      {id:'sandwichmaker', name:'توستر ساندويش', emoji:'🥪', aliases:['מכונת טוסט']},
      {id:'ricecooker', name:'طباخة رز', emoji:'🍚', aliases:['סיר אורז']},
      {id:'dishrack', name:'رف تنشيف صحون', emoji:'🍽️', aliases:['מעמד לכלים']},
      {id:'dishtowel', name:'فوطة مطبخ', emoji:'🧻', aliases:['منشفة مطبخ','מגבת מטבח']},
      {id:'ovenmitt', name:'قفاز فرن', emoji:'🧤', aliases:['כפפת תנור']},
      {id:'apron', name:'مريلة مطبخ', emoji:'🧑‍🍳', aliases:['סינר מטבח']},
      {id:'knifeblock', name:'حامل سكاكين', emoji:'🔪', aliases:['מעמד לסכינים']},
      {id:'potholder', name:'ماسك حراري', emoji:'🧤', aliases:['מטלית חמה']}
    ]}
  ];
